// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kubemq.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace KubeMQ.Contract.SDK.Grpc
{
  internal static partial class kubemq
  {
    static readonly string __ServiceName = "kubemq.kubemq";

    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.Event> __Marshaller_Event = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.Event.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.Result> __Marshaller_Result = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.Result.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.Subscribe> __Marshaller_Subscribe = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.Subscribe.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.EventReceive> __Marshaller_EventReceive = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.EventReceive.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.Response> __Marshaller_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.Response.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.QueueMessage> __Marshaller_QueueMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.QueueMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult> __Marshaller_SendQueueMessageResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest> __Marshaller_QueueMessagesBatchRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse> __Marshaller_QueueMessagesBatchResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest> __Marshaller_ReceiveQueueMessagesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse> __Marshaller_ReceiveQueueMessagesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest> __Marshaller_StreamQueueMessagesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse> __Marshaller_StreamQueueMessagesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest> __Marshaller_AckAllQueueMessagesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse> __Marshaller_AckAllQueueMessagesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.PingResult> __Marshaller_PingResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.PingResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.PollRequest> __Marshaller_PollRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.PollRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::KubeMQ.Contract.SDK.Grpc.PollResponse> __Marshaller_PollResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::KubeMQ.Contract.SDK.Grpc.PollResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Event, global::KubeMQ.Contract.SDK.Grpc.Result> __Method_SendEvent = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Event, global::KubeMQ.Contract.SDK.Grpc.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendEvent",
        __Marshaller_Event,
        __Marshaller_Result);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Event, global::KubeMQ.Contract.SDK.Grpc.Result> __Method_SendEventsStream = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Event, global::KubeMQ.Contract.SDK.Grpc.Result>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SendEventsStream",
        __Marshaller_Event,
        __Marshaller_Result);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Subscribe, global::KubeMQ.Contract.SDK.Grpc.EventReceive> __Method_SubscribeToEvents = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Subscribe, global::KubeMQ.Contract.SDK.Grpc.EventReceive>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeToEvents",
        __Marshaller_Subscribe,
        __Marshaller_EventReceive);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Subscribe, global::KubeMQ.Contract.SDK.Grpc.Request> __Method_SubscribeToRequests = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Subscribe, global::KubeMQ.Contract.SDK.Grpc.Request>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeToRequests",
        __Marshaller_Subscribe,
        __Marshaller_Request);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Request, global::KubeMQ.Contract.SDK.Grpc.Response> __Method_SendRequest = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Request, global::KubeMQ.Contract.SDK.Grpc.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendRequest",
        __Marshaller_Request,
        __Marshaller_Response);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Response, global::KubeMQ.Contract.SDK.Grpc.Empty> __Method_SendResponse = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Response, global::KubeMQ.Contract.SDK.Grpc.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendResponse",
        __Marshaller_Response,
        __Marshaller_Empty);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.QueueMessage, global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult> __Method_SendQueueMessage = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.QueueMessage, global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendQueueMessage",
        __Marshaller_QueueMessage,
        __Marshaller_SendQueueMessageResult);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest, global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse> __Method_SendQueueMessagesBatch = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest, global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendQueueMessagesBatch",
        __Marshaller_QueueMessagesBatchRequest,
        __Marshaller_QueueMessagesBatchResponse);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse> __Method_ReceiveQueueMessages = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReceiveQueueMessages",
        __Marshaller_ReceiveQueueMessagesRequest,
        __Marshaller_ReceiveQueueMessagesResponse);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse> __Method_StreamQueueMessage = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "StreamQueueMessage",
        __Marshaller_StreamQueueMessagesRequest,
        __Marshaller_StreamQueueMessagesResponse);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse> __Method_AckAllQueueMessages = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AckAllQueueMessages",
        __Marshaller_AckAllQueueMessagesRequest,
        __Marshaller_AckAllQueueMessagesResponse);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Empty, global::KubeMQ.Contract.SDK.Grpc.PingResult> __Method_Ping = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.Empty, global::KubeMQ.Contract.SDK.Grpc.PingResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_Empty,
        __Marshaller_PingResult);

    static readonly grpc::Method<global::KubeMQ.Contract.SDK.Grpc.PollRequest, global::KubeMQ.Contract.SDK.Grpc.PollResponse> __Method_Poll = new grpc::Method<global::KubeMQ.Contract.SDK.Grpc.PollRequest, global::KubeMQ.Contract.SDK.Grpc.PollResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Poll",
        __Marshaller_PollRequest,
        __Marshaller_PollResponse);

    /// <summary>Service descriptor</summary>
    internal static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::KubeMQ.Contract.SDK.Grpc.KubemqReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of kubemq</summary>
    internal abstract partial class kubemqBase
    {
      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.Result> SendEvent(global::KubeMQ.Contract.SDK.Grpc.Event request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SendEventsStream(grpc::IAsyncStreamReader<global::KubeMQ.Contract.SDK.Grpc.Event> requestStream, grpc::IServerStreamWriter<global::KubeMQ.Contract.SDK.Grpc.Result> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SubscribeToEvents(global::KubeMQ.Contract.SDK.Grpc.Subscribe request, grpc::IServerStreamWriter<global::KubeMQ.Contract.SDK.Grpc.EventReceive> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SubscribeToRequests(global::KubeMQ.Contract.SDK.Grpc.Subscribe request, grpc::IServerStreamWriter<global::KubeMQ.Contract.SDK.Grpc.Request> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.Response> SendRequest(global::KubeMQ.Contract.SDK.Grpc.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.Empty> SendResponse(global::KubeMQ.Contract.SDK.Grpc.Response request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult> SendQueueMessage(global::KubeMQ.Contract.SDK.Grpc.QueueMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse> SendQueueMessagesBatch(global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse> ReceiveQueueMessages(global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task StreamQueueMessage(grpc::IAsyncStreamReader<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest> requestStream, grpc::IServerStreamWriter<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse> AckAllQueueMessages(global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::KubeMQ.Contract.SDK.Grpc.PingResult> Ping(global::KubeMQ.Contract.SDK.Grpc.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Poll(grpc::IAsyncStreamReader<global::KubeMQ.Contract.SDK.Grpc.PollRequest> requestStream, grpc::IServerStreamWriter<global::KubeMQ.Contract.SDK.Grpc.PollResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for kubemq</summary>
    public partial class kubemqClient : grpc::ClientBase<kubemqClient>
    {
      /// <summary>Creates a new client for kubemq</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public kubemqClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for kubemq that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public kubemqClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected kubemqClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected kubemqClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::KubeMQ.Contract.SDK.Grpc.Result SendEvent(global::KubeMQ.Contract.SDK.Grpc.Event request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.Result SendEvent(global::KubeMQ.Contract.SDK.Grpc.Event request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.Result> SendEventAsync(global::KubeMQ.Contract.SDK.Grpc.Event request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.Result> SendEventAsync(global::KubeMQ.Contract.SDK.Grpc.Event request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendEvent, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::KubeMQ.Contract.SDK.Grpc.Event, global::KubeMQ.Contract.SDK.Grpc.Result> SendEventsStream(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendEventsStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::KubeMQ.Contract.SDK.Grpc.Event, global::KubeMQ.Contract.SDK.Grpc.Result> SendEventsStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SendEventsStream, null, options);
      }
      public virtual grpc::AsyncServerStreamingCall<global::KubeMQ.Contract.SDK.Grpc.EventReceive> SubscribeToEvents(global::KubeMQ.Contract.SDK.Grpc.Subscribe request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubscribeToEvents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::KubeMQ.Contract.SDK.Grpc.EventReceive> SubscribeToEvents(global::KubeMQ.Contract.SDK.Grpc.Subscribe request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeToEvents, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::KubeMQ.Contract.SDK.Grpc.Request> SubscribeToRequests(global::KubeMQ.Contract.SDK.Grpc.Subscribe request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubscribeToRequests(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::KubeMQ.Contract.SDK.Grpc.Request> SubscribeToRequests(global::KubeMQ.Contract.SDK.Grpc.Subscribe request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeToRequests, null, options, request);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.Response SendRequest(global::KubeMQ.Contract.SDK.Grpc.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendRequest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.Response SendRequest(global::KubeMQ.Contract.SDK.Grpc.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendRequest, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.Response> SendRequestAsync(global::KubeMQ.Contract.SDK.Grpc.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendRequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.Response> SendRequestAsync(global::KubeMQ.Contract.SDK.Grpc.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendRequest, null, options, request);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.Empty SendResponse(global::KubeMQ.Contract.SDK.Grpc.Response request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendResponse(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.Empty SendResponse(global::KubeMQ.Contract.SDK.Grpc.Response request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendResponse, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.Empty> SendResponseAsync(global::KubeMQ.Contract.SDK.Grpc.Response request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendResponseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.Empty> SendResponseAsync(global::KubeMQ.Contract.SDK.Grpc.Response request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendResponse, null, options, request);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult SendQueueMessage(global::KubeMQ.Contract.SDK.Grpc.QueueMessage request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendQueueMessage(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult SendQueueMessage(global::KubeMQ.Contract.SDK.Grpc.QueueMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendQueueMessage, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult> SendQueueMessageAsync(global::KubeMQ.Contract.SDK.Grpc.QueueMessage request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendQueueMessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.SendQueueMessageResult> SendQueueMessageAsync(global::KubeMQ.Contract.SDK.Grpc.QueueMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendQueueMessage, null, options, request);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse SendQueueMessagesBatch(global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendQueueMessagesBatch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse SendQueueMessagesBatch(global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendQueueMessagesBatch, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse> SendQueueMessagesBatchAsync(global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendQueueMessagesBatchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchResponse> SendQueueMessagesBatchAsync(global::KubeMQ.Contract.SDK.Grpc.QueueMessagesBatchRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendQueueMessagesBatch, null, options, request);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse ReceiveQueueMessages(global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ReceiveQueueMessages(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse ReceiveQueueMessages(global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReceiveQueueMessages, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse> ReceiveQueueMessagesAsync(global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ReceiveQueueMessagesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesResponse> ReceiveQueueMessagesAsync(global::KubeMQ.Contract.SDK.Grpc.ReceiveQueueMessagesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReceiveQueueMessages, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse> StreamQueueMessage(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StreamQueueMessage(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesRequest, global::KubeMQ.Contract.SDK.Grpc.StreamQueueMessagesResponse> StreamQueueMessage(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_StreamQueueMessage, null, options);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse AckAllQueueMessages(global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AckAllQueueMessages(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse AckAllQueueMessages(global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AckAllQueueMessages, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse> AckAllQueueMessagesAsync(global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AckAllQueueMessagesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesResponse> AckAllQueueMessagesAsync(global::KubeMQ.Contract.SDK.Grpc.AckAllQueueMessagesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AckAllQueueMessages, null, options, request);
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.PingResult Ping(global::KubeMQ.Contract.SDK.Grpc.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::KubeMQ.Contract.SDK.Grpc.PingResult Ping(global::KubeMQ.Contract.SDK.Grpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.PingResult> PingAsync(global::KubeMQ.Contract.SDK.Grpc.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::KubeMQ.Contract.SDK.Grpc.PingResult> PingAsync(global::KubeMQ.Contract.SDK.Grpc.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::KubeMQ.Contract.SDK.Grpc.PollRequest, global::KubeMQ.Contract.SDK.Grpc.PollResponse> Poll(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Poll(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::KubeMQ.Contract.SDK.Grpc.PollRequest, global::KubeMQ.Contract.SDK.Grpc.PollResponse> Poll(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Poll, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override kubemqClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new kubemqClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    internal static grpc::ServerServiceDefinition BindService(kubemqBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendEvent, serviceImpl.SendEvent)
          .AddMethod(__Method_SendEventsStream, serviceImpl.SendEventsStream)
          .AddMethod(__Method_SubscribeToEvents, serviceImpl.SubscribeToEvents)
          .AddMethod(__Method_SubscribeToRequests, serviceImpl.SubscribeToRequests)
          .AddMethod(__Method_SendRequest, serviceImpl.SendRequest)
          .AddMethod(__Method_SendResponse, serviceImpl.SendResponse)
          .AddMethod(__Method_SendQueueMessage, serviceImpl.SendQueueMessage)
          .AddMethod(__Method_SendQueueMessagesBatch, serviceImpl.SendQueueMessagesBatch)
          .AddMethod(__Method_ReceiveQueueMessages, serviceImpl.ReceiveQueueMessages)
          .AddMethod(__Method_StreamQueueMessage, serviceImpl.StreamQueueMessage)
          .AddMethod(__Method_AckAllQueueMessages, serviceImpl.AckAllQueueMessages)
          .AddMethod(__Method_Ping, serviceImpl.Ping)
          .AddMethod(__Method_Poll, serviceImpl.Poll).Build();
    }

  }
}
#endregion
